language: scala

jdk:
  - openjdk8

scala:
  - 2.12.2
  - 2.13.2

install:
  - nvm list
  - nvm install 5.10.0
  - nvm use 5.10.0

before_script:
  # Init xvfb for headless browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Start test server
  - cd test/server && npm install && node index.js &

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - test/update-readme-sanity-check.sh --fatalDiff
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJS/test
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJVM/test
  # - sbt ++$TRAVIS_SCALA_VERSION firefox:test
