language: scala

jdk:
  - openjdk8

scala:
  - 2.12.11
  - 2.13.2

install:
  - nvm list
  - nvm install 5.10.0
  - nvm use 5.10.0
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
  # Start test server
  - cd test/server && npm install && node index.js &

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - test/update-readme-sanity-check.sh --fatalDiff
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJS/test
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJVM/test
  # - sbt ++$TRAVIS_SCALA_VERSION firefox:test
